export interface CountryEntry {
  readonly code: string;
  readonly name: string;
  readonly aliases: readonly string[];
}

export const countries: readonly CountryEntry[] = Object.freeze([
  { code: "AD", name: "Andorra", aliases: ["AD", "AND", "Andorra", "Principality of Andorra"] },
  { code: "AE", name: "United Arab Emirates", aliases: ["AE", "ARE", "United Arab Emirates"] },
  { code: "AF", name: "Afghanistan", aliases: ["AF", "AFG", "Afghanistan", "Islamic Republic of Afghanistan"] },
  { code: "AG", name: "Antigua and Barbuda", aliases: ["AG", "ATG", "Antigua and Barbuda"] },
  { code: "AI", name: "Anguilla", aliases: ["AI", "AIA", "Anguilla"] },
  { code: "AL", name: "Albania", aliases: ["AL", "ALB", "Albania", "Republic of Albania"] },
  { code: "AM", name: "Armenia", aliases: ["AM", "ARM", "Armenia", "Republic of Armenia"] },
  { code: "AO", name: "Angola", aliases: ["AO", "AGO", "Angola", "Republic of Angola"] },
  { code: "AQ", name: "Antarctica", aliases: ["AQ", "ATA", "Antarctica"] },
  { code: "AR", name: "Argentina", aliases: ["AR", "ARG", "Argentina", "Argentine Republic"] },
  { code: "AS", name: "American Samoa", aliases: ["AS", "ASM", "American Samoa"] },
  { code: "AT", name: "Austria", aliases: ["AT", "AUT", "Austria", "Republic of Austria"] },
  { code: "AU", name: "Australia", aliases: ["AU", "AUS", "Australia"] },
  { code: "AW", name: "Aruba", aliases: ["AW", "ABW", "Aruba"] },
  { code: "AX", name: "\u00c5land Islands", aliases: ["AX", "ALA", "Åland Islands"] },
  { code: "AZ", name: "Azerbaijan", aliases: ["AZ", "AZE", "Azerbaijan", "Republic of Azerbaijan"] },
  { code: "BA", name: "Bosnia and Herzegovina", aliases: ["BA", "BIH", "Bosnia and Herzegovina", "Republic of Bosnia and Herzegovina"] },
  { code: "BB", name: "Barbados", aliases: ["BB", "BRB", "Barbados"] },
  { code: "BD", name: "Bangladesh", aliases: ["BD", "BGD", "Bangladesh", "People's Republic of Bangladesh"] },
  { code: "BE", name: "Belgium", aliases: ["BE", "BEL", "Belgium", "Kingdom of Belgium"] },
  { code: "BF", name: "Burkina Faso", aliases: ["BF", "BFA", "Burkina Faso"] },
  { code: "BG", name: "Bulgaria", aliases: ["BG", "BGR", "Bulgaria", "Republic of Bulgaria"] },
  { code: "BH", name: "Bahrain", aliases: ["BH", "BHR", "Bahrain", "Kingdom of Bahrain"] },
  { code: "BI", name: "Burundi", aliases: ["BI", "BDI", "Burundi", "Republic of Burundi"] },
  { code: "BJ", name: "Benin", aliases: ["BJ", "BEN", "Benin", "Republic of Benin"] },
  { code: "BL", name: "Saint Barth\u00e9lemy", aliases: ["BL", "BLM", "Saint Barthélemy"] },
  { code: "BM", name: "Bermuda", aliases: ["BM", "BMU", "Bermuda"] },
  { code: "BN", name: "Brunei Darussalam", aliases: ["BN", "BRN", "Brunei Darussalam", "Brunei"] },
  { code: "BO", name: "Bolivia, Plurinational State of", aliases: ["BO", "BOL", "Bolivia, Plurinational State of", "Plurinational State of Bolivia", "Bolivia"] },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", aliases: ["BQ", "BES", "Bonaire, Sint Eustatius and Saba"] },
  { code: "BR", name: "Brazil", aliases: ["BR", "BRA", "Brazil", "Federative Republic of Brazil"] },
  { code: "BS", name: "Bahamas", aliases: ["BS", "BHS", "Bahamas", "Commonwealth of the Bahamas"] },
  { code: "BT", name: "Bhutan", aliases: ["BT", "BTN", "Bhutan", "Kingdom of Bhutan"] },
  { code: "BV", name: "Bouvet Island", aliases: ["BV", "BVT", "Bouvet Island"] },
  { code: "BW", name: "Botswana", aliases: ["BW", "BWA", "Botswana", "Republic of Botswana"] },
  { code: "BY", name: "Belarus", aliases: ["BY", "BLR", "Belarus", "Republic of Belarus"] },
  { code: "BZ", name: "Belize", aliases: ["BZ", "BLZ", "Belize"] },
  { code: "CA", name: "Canada", aliases: ["CA", "CAN", "Canada"] },
  { code: "CC", name: "Cocos (Keeling) Islands", aliases: ["CC", "CCK", "Cocos (Keeling) Islands"] },
  { code: "CD", name: "Congo, The Democratic Republic of the", aliases: ["CD", "COD", "Congo, The Democratic Republic of the", "DR Congo", "Democratic Republic of the Congo"] },
  { code: "CF", name: "Central African Republic", aliases: ["CF", "CAF", "Central African Republic"] },
  { code: "CG", name: "Congo", aliases: ["CG", "COG", "Congo", "Republic of the Congo"] },
  { code: "CH", name: "Switzerland", aliases: ["CH", "CHE", "Switzerland", "Swiss Confederation"] },
  { code: "CI", name: "C\u00f4te d'Ivoire", aliases: ["CI", "CIV", "Côte d'Ivoire", "Republic of Côte d'Ivoire", "Ivory Coast"] },
  { code: "CK", name: "Cook Islands", aliases: ["CK", "COK", "Cook Islands"] },
  { code: "CL", name: "Chile", aliases: ["CL", "CHL", "Chile", "Republic of Chile"] },
  { code: "CM", name: "Cameroon", aliases: ["CM", "CMR", "Cameroon", "Republic of Cameroon"] },
  { code: "CN", name: "China", aliases: ["CN", "CHN", "China", "People's Republic of China"] },
  { code: "CO", name: "Colombia", aliases: ["CO", "COL", "Colombia", "Republic of Colombia"] },
  { code: "CR", name: "Costa Rica", aliases: ["CR", "CRI", "Costa Rica", "Republic of Costa Rica"] },
  { code: "CU", name: "Cuba", aliases: ["CU", "CUB", "Cuba", "Republic of Cuba"] },
  { code: "CV", name: "Cabo Verde", aliases: ["CV", "CPV", "Cabo Verde", "Republic of Cabo Verde", "Cape Verde"] },
  { code: "CW", name: "Cura\u00e7ao", aliases: ["CW", "CUW", "Curaçao"] },
  { code: "CX", name: "Christmas Island", aliases: ["CX", "CXR", "Christmas Island"] },
  { code: "CY", name: "Cyprus", aliases: ["CY", "CYP", "Cyprus", "Republic of Cyprus"] },
  { code: "CZ", name: "Czechia", aliases: ["CZ", "CZE", "Czechia", "Czech Republic"] },
  { code: "DE", name: "Germany", aliases: ["DE", "DEU", "Germany", "Federal Republic of Germany"] },
  { code: "DJ", name: "Djibouti", aliases: ["DJ", "DJI", "Djibouti", "Republic of Djibouti"] },
  { code: "DK", name: "Denmark", aliases: ["DK", "DNK", "Denmark", "Kingdom of Denmark"] },
  { code: "DM", name: "Dominica", aliases: ["DM", "DMA", "Dominica", "Commonwealth of Dominica"] },
  { code: "DO", name: "Dominican Republic", aliases: ["DO", "DOM", "Dominican Republic"] },
  { code: "DZ", name: "Algeria", aliases: ["DZ", "DZA", "Algeria", "People's Democratic Republic of Algeria"] },
  { code: "EC", name: "Ecuador", aliases: ["EC", "ECU", "Ecuador", "Republic of Ecuador"] },
  { code: "EE", name: "Estonia", aliases: ["EE", "EST", "Estonia", "Republic of Estonia"] },
  { code: "EG", name: "Egypt", aliases: ["EG", "EGY", "Egypt", "Arab Republic of Egypt"] },
  { code: "EH", name: "Western Sahara", aliases: ["EH", "ESH", "Western Sahara"] },
  { code: "ER", name: "Eritrea", aliases: ["ER", "ERI", "Eritrea", "the State of Eritrea"] },
  { code: "ES", name: "Spain", aliases: ["ES", "ESP", "Spain", "Kingdom of Spain"] },
  { code: "ET", name: "Ethiopia", aliases: ["ET", "ETH", "Ethiopia", "Federal Democratic Republic of Ethiopia"] },
  { code: "FI", name: "Finland", aliases: ["FI", "FIN", "Finland", "Republic of Finland"] },
  { code: "FJ", name: "Fiji", aliases: ["FJ", "FJI", "Fiji", "Republic of Fiji"] },
  { code: "FK", name: "Falkland Islands (Malvinas)", aliases: ["FK", "FLK", "Falkland Islands (Malvinas)"] },
  { code: "FM", name: "Micronesia, Federated States of", aliases: ["FM", "FSM", "Micronesia, Federated States of", "Federated States of Micronesia"] },
  { code: "FO", name: "Faroe Islands", aliases: ["FO", "FRO", "Faroe Islands"] },
  { code: "FR", name: "France", aliases: ["FR", "FRA", "France", "French Republic"] },
  { code: "GA", name: "Gabon", aliases: ["GA", "GAB", "Gabon", "Gabonese Republic"] },
  { code: "GB", name: "United Kingdom", aliases: ["GB", "GBR", "United Kingdom", "United Kingdom of Great Britain and Northern Ireland", "UK", "Great Britain", "Britain"] },
  { code: "GD", name: "Grenada", aliases: ["GD", "GRD", "Grenada"] },
  { code: "GE", name: "Georgia", aliases: ["GE", "GEO", "Georgia"] },
  { code: "GF", name: "French Guiana", aliases: ["GF", "GUF", "French Guiana"] },
  { code: "GG", name: "Guernsey", aliases: ["GG", "GGY", "Guernsey"] },
  { code: "GH", name: "Ghana", aliases: ["GH", "GHA", "Ghana", "Republic of Ghana"] },
  { code: "GI", name: "Gibraltar", aliases: ["GI", "GIB", "Gibraltar"] },
  { code: "GL", name: "Greenland", aliases: ["GL", "GRL", "Greenland"] },
  { code: "GM", name: "Gambia", aliases: ["GM", "GMB", "Gambia", "Islamic Republic of the Gambia"] },
  { code: "GN", name: "Guinea", aliases: ["GN", "GIN", "Guinea", "Republic of Guinea"] },
  { code: "GP", name: "Guadeloupe", aliases: ["GP", "GLP", "Guadeloupe"] },
  { code: "GQ", name: "Equatorial Guinea", aliases: ["GQ", "GNQ", "Equatorial Guinea", "Republic of Equatorial Guinea"] },
  { code: "GR", name: "Greece", aliases: ["GR", "GRC", "Greece", "Hellenic Republic"] },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", aliases: ["GS", "SGS", "South Georgia and the South Sandwich Islands"] },
  { code: "GT", name: "Guatemala", aliases: ["GT", "GTM", "Guatemala", "Republic of Guatemala"] },
  { code: "GU", name: "Guam", aliases: ["GU", "GUM", "Guam"] },
  { code: "GW", name: "Guinea-Bissau", aliases: ["GW", "GNB", "Guinea-Bissau", "Republic of Guinea-Bissau"] },
  { code: "GY", name: "Guyana", aliases: ["GY", "GUY", "Guyana", "Republic of Guyana"] },
  { code: "HK", name: "Hong Kong", aliases: ["HK", "HKG", "Hong Kong", "Hong Kong Special Administrative Region of China"] },
  { code: "HM", name: "Heard Island and McDonald Islands", aliases: ["HM", "HMD", "Heard Island and McDonald Islands"] },
  { code: "HN", name: "Honduras", aliases: ["HN", "HND", "Honduras", "Republic of Honduras"] },
  { code: "HR", name: "Croatia", aliases: ["HR", "HRV", "Croatia", "Republic of Croatia"] },
  { code: "HT", name: "Haiti", aliases: ["HT", "HTI", "Haiti", "Republic of Haiti"] },
  { code: "HU", name: "Hungary", aliases: ["HU", "HUN", "Hungary"] },
  { code: "ID", name: "Indonesia", aliases: ["ID", "IDN", "Indonesia", "Republic of Indonesia"] },
  { code: "IE", name: "Ireland", aliases: ["IE", "IRL", "Ireland"] },
  { code: "IL", name: "Israel", aliases: ["IL", "ISR", "Israel", "State of Israel"] },
  { code: "IM", name: "Isle of Man", aliases: ["IM", "IMN", "Isle of Man"] },
  { code: "IN", name: "India", aliases: ["IN", "IND", "India", "Republic of India"] },
  { code: "IO", name: "British Indian Ocean Territory", aliases: ["IO", "IOT", "British Indian Ocean Territory"] },
  { code: "IQ", name: "Iraq", aliases: ["IQ", "IRQ", "Iraq", "Republic of Iraq"] },
  { code: "IR", name: "Iran, Islamic Republic of", aliases: ["IR", "IRN", "Iran, Islamic Republic of", "Islamic Republic of Iran", "Iran"] },
  { code: "IS", name: "Iceland", aliases: ["IS", "ISL", "Iceland", "Republic of Iceland"] },
  { code: "IT", name: "Italy", aliases: ["IT", "ITA", "Italy", "Italian Republic"] },
  { code: "JE", name: "Jersey", aliases: ["JE", "JEY", "Jersey"] },
  { code: "JM", name: "Jamaica", aliases: ["JM", "JAM", "Jamaica"] },
  { code: "JO", name: "Jordan", aliases: ["JO", "JOR", "Jordan", "Hashemite Kingdom of Jordan"] },
  { code: "JP", name: "Japan", aliases: ["JP", "JPN", "Japan"] },
  { code: "KE", name: "Kenya", aliases: ["KE", "KEN", "Kenya", "Republic of Kenya"] },
  { code: "KG", name: "Kyrgyzstan", aliases: ["KG", "KGZ", "Kyrgyzstan", "Kyrgyz Republic"] },
  { code: "KH", name: "Cambodia", aliases: ["KH", "KHM", "Cambodia", "Kingdom of Cambodia"] },
  { code: "KI", name: "Kiribati", aliases: ["KI", "KIR", "Kiribati", "Republic of Kiribati"] },
  { code: "KM", name: "Comoros", aliases: ["KM", "COM", "Comoros", "Union of the Comoros"] },
  { code: "KN", name: "Saint Kitts and Nevis", aliases: ["KN", "KNA", "Saint Kitts and Nevis"] },
  { code: "KP", name: "Korea, Democratic People's Republic of", aliases: ["KP", "PRK", "Korea, Democratic People's Republic of", "Democratic People's Republic of Korea", "North Korea"] },
  { code: "KR", name: "Korea, Republic of", aliases: ["KR", "KOR", "Korea, Republic of", "South Korea"] },
  { code: "KW", name: "Kuwait", aliases: ["KW", "KWT", "Kuwait", "State of Kuwait"] },
  { code: "KY", name: "Cayman Islands", aliases: ["KY", "CYM", "Cayman Islands"] },
  { code: "KZ", name: "Kazakhstan", aliases: ["KZ", "KAZ", "Kazakhstan", "Republic of Kazakhstan"] },
  { code: "LA", name: "Lao People's Democratic Republic", aliases: ["LA", "LAO", "Lao People's Democratic Republic", "Laos"] },
  { code: "LB", name: "Lebanon", aliases: ["LB", "LBN", "Lebanon", "Lebanese Republic"] },
  { code: "LC", name: "Saint Lucia", aliases: ["LC", "LCA", "Saint Lucia"] },
  { code: "LI", name: "Liechtenstein", aliases: ["LI", "LIE", "Liechtenstein", "Principality of Liechtenstein"] },
  { code: "LK", name: "Sri Lanka", aliases: ["LK", "LKA", "Sri Lanka", "Democratic Socialist Republic of Sri Lanka"] },
  { code: "LR", name: "Liberia", aliases: ["LR", "LBR", "Liberia", "Republic of Liberia"] },
  { code: "LS", name: "Lesotho", aliases: ["LS", "LSO", "Lesotho", "Kingdom of Lesotho"] },
  { code: "LT", name: "Lithuania", aliases: ["LT", "LTU", "Lithuania", "Republic of Lithuania"] },
  { code: "LU", name: "Luxembourg", aliases: ["LU", "LUX", "Luxembourg", "Grand Duchy of Luxembourg"] },
  { code: "LV", name: "Latvia", aliases: ["LV", "LVA", "Latvia", "Republic of Latvia"] },
  { code: "LY", name: "Libya", aliases: ["LY", "LBY", "Libya"] },
  { code: "MA", name: "Morocco", aliases: ["MA", "MAR", "Morocco", "Kingdom of Morocco"] },
  { code: "MC", name: "Monaco", aliases: ["MC", "MCO", "Monaco", "Principality of Monaco"] },
  { code: "MD", name: "Moldova, Republic of", aliases: ["MD", "MDA", "Moldova, Republic of", "Republic of Moldova", "Moldova"] },
  { code: "ME", name: "Montenegro", aliases: ["ME", "MNE", "Montenegro"] },
  { code: "MF", name: "Saint Martin (French part)", aliases: ["MF", "MAF", "Saint Martin (French part)"] },
  { code: "MG", name: "Madagascar", aliases: ["MG", "MDG", "Madagascar", "Republic of Madagascar"] },
  { code: "MH", name: "Marshall Islands", aliases: ["MH", "MHL", "Marshall Islands", "Republic of the Marshall Islands"] },
  { code: "MK", name: "Macedonia, Republic of", aliases: ["MK", "MKD", "Macedonia, Republic of", "The Former Yugoslav Republic of Macedonia"] },
  { code: "ML", name: "Mali", aliases: ["ML", "MLI", "Mali", "Republic of Mali"] },
  { code: "MM", name: "Myanmar", aliases: ["MM", "MMR", "Myanmar", "Republic of Myanmar"] },
  { code: "MN", name: "Mongolia", aliases: ["MN", "MNG", "Mongolia"] },
  { code: "MO", name: "Macao", aliases: ["MO", "MAC", "Macao", "Macao Special Administrative Region of China"] },
  { code: "MP", name: "Northern Mariana Islands", aliases: ["MP", "MNP", "Northern Mariana Islands", "Commonwealth of the Northern Mariana Islands"] },
  { code: "MQ", name: "Martinique", aliases: ["MQ", "MTQ", "Martinique"] },
  { code: "MR", name: "Mauritania", aliases: ["MR", "MRT", "Mauritania", "Islamic Republic of Mauritania"] },
  { code: "MS", name: "Montserrat", aliases: ["MS", "MSR", "Montserrat"] },
  { code: "MT", name: "Malta", aliases: ["MT", "MLT", "Malta", "Republic of Malta"] },
  { code: "MU", name: "Mauritius", aliases: ["MU", "MUS", "Mauritius", "Republic of Mauritius"] },
  { code: "MV", name: "Maldives", aliases: ["MV", "MDV", "Maldives", "Republic of Maldives"] },
  { code: "MW", name: "Malawi", aliases: ["MW", "MWI", "Malawi", "Republic of Malawi"] },
  { code: "MX", name: "Mexico", aliases: ["MX", "MEX", "Mexico", "United Mexican States"] },
  { code: "MY", name: "Malaysia", aliases: ["MY", "MYS", "Malaysia"] },
  { code: "MZ", name: "Mozambique", aliases: ["MZ", "MOZ", "Mozambique", "Republic of Mozambique"] },
  { code: "NA", name: "Namibia", aliases: ["NA", "NAM", "Namibia", "Republic of Namibia"] },
  { code: "NC", name: "New Caledonia", aliases: ["NC", "NCL", "New Caledonia"] },
  { code: "NE", name: "Niger", aliases: ["NE", "NER", "Niger", "Republic of the Niger"] },
  { code: "NF", name: "Norfolk Island", aliases: ["NF", "NFK", "Norfolk Island"] },
  { code: "NG", name: "Nigeria", aliases: ["NG", "NGA", "Nigeria", "Federal Republic of Nigeria"] },
  { code: "NI", name: "Nicaragua", aliases: ["NI", "NIC", "Nicaragua", "Republic of Nicaragua"] },
  { code: "NL", name: "Netherlands", aliases: ["NL", "NLD", "Netherlands", "Kingdom of the Netherlands"] },
  { code: "NO", name: "Norway", aliases: ["NO", "NOR", "Norway", "Kingdom of Norway"] },
  { code: "NP", name: "Nepal", aliases: ["NP", "NPL", "Nepal", "Federal Democratic Republic of Nepal"] },
  { code: "NR", name: "Nauru", aliases: ["NR", "NRU", "Nauru", "Republic of Nauru"] },
  { code: "NU", name: "Niue", aliases: ["NU", "NIU", "Niue"] },
  { code: "NZ", name: "New Zealand", aliases: ["NZ", "NZL", "New Zealand"] },
  { code: "OM", name: "Oman", aliases: ["OM", "OMN", "Oman", "Sultanate of Oman"] },
  { code: "PA", name: "Panama", aliases: ["PA", "PAN", "Panama", "Republic of Panama"] },
  { code: "PE", name: "Peru", aliases: ["PE", "PER", "Peru", "Republic of Peru"] },
  { code: "PF", name: "French Polynesia", aliases: ["PF", "PYF", "French Polynesia"] },
  { code: "PG", name: "Papua New Guinea", aliases: ["PG", "PNG", "Papua New Guinea", "Independent State of Papua New Guinea"] },
  { code: "PH", name: "Philippines", aliases: ["PH", "PHL", "Philippines", "Republic of the Philippines", "Philippine"] },
  { code: "PK", name: "Pakistan", aliases: ["PK", "PAK", "Pakistan", "Islamic Republic of Pakistan"] },
  { code: "PL", name: "Poland", aliases: ["PL", "POL", "Poland", "Republic of Poland"] },
  { code: "PM", name: "Saint Pierre and Miquelon", aliases: ["PM", "SPM", "Saint Pierre and Miquelon"] },
  { code: "PN", name: "Pitcairn", aliases: ["PN", "PCN", "Pitcairn"] },
  { code: "PR", name: "Puerto Rico", aliases: ["PR", "PRI", "Puerto Rico"] },
  { code: "PS", name: "Palestine, State of", aliases: ["PS", "PSE", "Palestine, State of", "the State of Palestine", "Palestine"] },
  { code: "PT", name: "Portugal", aliases: ["PT", "PRT", "Portugal", "Portuguese Republic"] },
  { code: "PW", name: "Palau", aliases: ["PW", "PLW", "Palau", "Republic of Palau"] },
  { code: "PY", name: "Paraguay", aliases: ["PY", "PRY", "Paraguay", "Republic of Paraguay"] },
  { code: "QA", name: "Qatar", aliases: ["QA", "QAT", "Qatar", "State of Qatar"] },
  { code: "RE", name: "R\u00e9union", aliases: ["RE", "REU", "Réunion"] },
  { code: "RO", name: "Romania", aliases: ["RO", "ROU", "Romania"] },
  { code: "RS", name: "Serbia", aliases: ["RS", "SRB", "Serbia", "Republic of Serbia"] },
  { code: "RU", name: "Russian Federation", aliases: ["RU", "RUS", "Russian Federation", "Russia"] },
  { code: "RW", name: "Rwanda", aliases: ["RW", "RWA", "Rwanda", "Rwandese Republic"] },
  { code: "SA", name: "Saudi Arabia", aliases: ["SA", "SAU", "Saudi Arabia", "Kingdom of Saudi Arabia"] },
  { code: "SB", name: "Solomon Islands", aliases: ["SB", "SLB", "Solomon Islands"] },
  { code: "SC", name: "Seychelles", aliases: ["SC", "SYC", "Seychelles", "Republic of Seychelles"] },
  { code: "SD", name: "Sudan", aliases: ["SD", "SDN", "Sudan", "Republic of the Sudan"] },
  { code: "SE", name: "Sweden", aliases: ["SE", "SWE", "Sweden", "Kingdom of Sweden"] },
  { code: "SG", name: "Singapore", aliases: ["SG", "SGP", "Singapore", "Republic of Singapore"] },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", aliases: ["SH", "SHN", "Saint Helena, Ascension and Tristan da Cunha"] },
  { code: "SI", name: "Slovenia", aliases: ["SI", "SVN", "Slovenia", "Republic of Slovenia"] },
  { code: "SJ", name: "Svalbard and Jan Mayen", aliases: ["SJ", "SJM", "Svalbard and Jan Mayen"] },
  { code: "SK", name: "Slovakia", aliases: ["SK", "SVK", "Slovakia", "Slovak Republic"] },
  { code: "SL", name: "Sierra Leone", aliases: ["SL", "SLE", "Sierra Leone", "Republic of Sierra Leone"] },
  { code: "SM", name: "San Marino", aliases: ["SM", "SMR", "San Marino", "Republic of San Marino"] },
  { code: "SN", name: "Senegal", aliases: ["SN", "SEN", "Senegal", "Republic of Senegal"] },
  { code: "SO", name: "Somalia", aliases: ["SO", "SOM", "Somalia", "Federal Republic of Somalia"] },
  { code: "SR", name: "Suriname", aliases: ["SR", "SUR", "Suriname", "Republic of Suriname"] },
  { code: "SS", name: "South Sudan", aliases: ["SS", "SSD", "South Sudan", "Republic of South Sudan"] },
  { code: "ST", name: "Sao Tome and Principe", aliases: ["ST", "STP", "Sao Tome and Principe", "Democratic Republic of Sao Tome and Principe"] },
  { code: "SV", name: "El Salvador", aliases: ["SV", "SLV", "El Salvador", "Republic of El Salvador"] },
  { code: "SX", name: "Sint Maarten (Dutch part)", aliases: ["SX", "SXM", "Sint Maarten (Dutch part)"] },
  { code: "SY", name: "Syrian Arab Republic", aliases: ["SY", "SYR", "Syrian Arab Republic", "Syria"] },
  { code: "SZ", name: "Swaziland", aliases: ["SZ", "SWZ", "Swaziland", "Kingdom of Swaziland"] },
  { code: "TC", name: "Turks and Caicos Islands", aliases: ["TC", "TCA", "Turks and Caicos Islands"] },
  { code: "TD", name: "Chad", aliases: ["TD", "TCD", "Chad", "Republic of Chad"] },
  { code: "TF", name: "French Southern Territories", aliases: ["TF", "ATF", "French Southern Territories"] },
  { code: "TG", name: "Togo", aliases: ["TG", "TGO", "Togo", "Togolese Republic"] },
  { code: "TH", name: "Thailand", aliases: ["TH", "THA", "Thailand", "Kingdom of Thailand"] },
  { code: "TJ", name: "Tajikistan", aliases: ["TJ", "TJK", "Tajikistan", "Republic of Tajikistan"] },
  { code: "TK", name: "Tokelau", aliases: ["TK", "TKL", "Tokelau"] },
  { code: "TL", name: "Timor-Leste", aliases: ["TL", "TLS", "Timor-Leste", "Democratic Republic of Timor-Leste"] },
  { code: "TM", name: "Turkmenistan", aliases: ["TM", "TKM", "Turkmenistan"] },
  { code: "TN", name: "Tunisia", aliases: ["TN", "TUN", "Tunisia", "Republic of Tunisia"] },
  { code: "TO", name: "Tonga", aliases: ["TO", "TON", "Tonga", "Kingdom of Tonga"] },
  { code: "TR", name: "Turkey", aliases: ["TR", "TUR", "Turkey", "Republic of Turkey"] },
  { code: "TT", name: "Trinidad and Tobago", aliases: ["TT", "TTO", "Trinidad and Tobago", "Republic of Trinidad and Tobago"] },
  { code: "TV", name: "Tuvalu", aliases: ["TV", "TUV", "Tuvalu"] },
  { code: "TW", name: "Taiwan, Province of China", aliases: ["TW", "TWN", "Taiwan, Province of China", "Taiwan"] },
  { code: "TZ", name: "Tanzania, United Republic of", aliases: ["TZ", "TZA", "Tanzania, United Republic of", "United Republic of Tanzania", "Tanzania"] },
  { code: "UA", name: "Ukraine", aliases: ["UA", "UKR", "Ukraine"] },
  { code: "UG", name: "Uganda", aliases: ["UG", "UGA", "Uganda", "Republic of Uganda"] },
  { code: "UM", name: "United States Minor Outlying Islands", aliases: ["UM", "UMI", "United States Minor Outlying Islands"] },
  { code: "US", name: "United States", aliases: ["US", "USA", "United States", "United States of America", "America"] },
  { code: "UY", name: "Uruguay", aliases: ["UY", "URY", "Uruguay", "Eastern Republic of Uruguay"] },
  { code: "UZ", name: "Uzbekistan", aliases: ["UZ", "UZB", "Uzbekistan", "Republic of Uzbekistan"] },
  { code: "VA", name: "Holy See (Vatican City State)", aliases: ["VA", "VAT", "Holy See (Vatican City State)"] },
  { code: "VC", name: "Saint Vincent and the Grenadines", aliases: ["VC", "VCT", "Saint Vincent and the Grenadines"] },
  { code: "VE", name: "Venezuela, Bolivarian Republic of", aliases: ["VE", "VEN", "Venezuela, Bolivarian Republic of", "Bolivarian Republic of Venezuela", "Venezuela"] },
  { code: "VG", name: "Virgin Islands, British", aliases: ["VG", "VGB", "Virgin Islands, British", "British Virgin Islands"] },
  { code: "VI", name: "Virgin Islands, U.S.", aliases: ["VI", "VIR", "Virgin Islands, U.S.", "Virgin Islands of the United States"] },
  { code: "VN", name: "Viet Nam", aliases: ["VN", "VNM", "Viet Nam", "Socialist Republic of Viet Nam", "Vietnam"] },
  { code: "VU", name: "Vanuatu", aliases: ["VU", "VUT", "Vanuatu", "Republic of Vanuatu"] },
  { code: "WF", name: "Wallis and Futuna", aliases: ["WF", "WLF", "Wallis and Futuna"] },
  { code: "WS", name: "Samoa", aliases: ["WS", "WSM", "Samoa", "Independent State of Samoa"] },
  { code: "XK", name: "Kosovo", aliases: ["Kosovo"] },
  { code: "YE", name: "Yemen", aliases: ["YE", "YEM", "Yemen", "Republic of Yemen"] },
  { code: "YT", name: "Mayotte", aliases: ["YT", "MYT", "Mayotte"] },
  { code: "ZA", name: "South Africa", aliases: ["ZA", "ZAF", "South Africa", "Republic of South Africa"] },
  { code: "ZM", name: "Zambia", aliases: ["ZM", "ZMB", "Zambia", "Republic of Zambia"] },
  { code: "ZW", name: "Zimbabwe", aliases: ["ZW", "ZWE", "Zimbabwe", "Republic of Zimbabwe"] },
]);

function normalizeCountryTerm(value: string): string {
  return value.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

const countryByCode = new Map(countries.map((country) => [country.code, country]));
const aliasCandidates = new Map<string, string[]>();
for (const country of countries) {
  for (const alias of country.aliases) {
    const normalized = normalizeCountryTerm(alias);
    aliasCandidates.set(normalized, [...(aliasCandidates.get(normalized) ?? []), country.code]);
  }
}

export function resolveCountryQuery(query: string): string | undefined {
  const matches = aliasCandidates.get(normalizeCountryTerm(query));
  return matches?.length === 1 ? matches[0] : undefined;
}

export function isIsoCountryCode(code: string): boolean {
  return countryByCode.has(code);
}

export function countryName(code: string): string {
  return countryByCode.get(code)?.name ?? code;
}

export function countryFlag(code: string): string {
  if (!/^[A-Z]{2}$/.test(code)) return "";
  return String.fromCodePoint(...[...code].map((character) => 127397 + character.charCodeAt(0)));
}
